// #region zod-from-json
// import { maxLength, minLength } from '../node_modules/zod/v4/classic/checks.js';
// import {
//   date as isoDate,
//   datetime as isoDatetime,
//   duration as isoDuration,
//   time as isoTime,
// } from '../node_modules/zod/v4/classic/iso.js';
// import {
//   base64,
//   base64url,
//   cidrv4,
//   cidrv6,
//   e164,
//   ipv4,
//   ipv6,
//   jwt,
//   ksuid,
//   mac,
//   nanoid,
//   ulid,
//   url,
//   uuid,
//   xid,
//   email,
//   emoji,
//   any,
//   array,
//   boolean,
//   cuid,
//   cuid2,
//   enum as _enum,
//   intersection,
//   lazy,
//   literal,
//   looseRecord,
//   never,
//   null as _null,
//   nullable,
//   number,
//   object,
//   readonly,
//   record,
//   string,
//   tuple,
//   union,
//   xor,
// } from '../node_modules/zod/v4/classic/schemas.js';

// const forZondFromJSON = {
//   any,
//   array,
//   base64,
//   base64url,
//   boolean,
//   cidrv4,
//   cidrv6,
//   cuid,
//   cuid2,
//   e164,
//   email,
//   emoji,
//   enum: _enum,
//   intersection,
//   ipv4,
//   ipv6,
//   iso: {
//     date: isoDate,
//     datetime: isoDatetime,
//     duration: isoDuration,
//     time: isoTime,
//   },
//   jwt,
//   ksuid,
//   lazy,
//   literal,
//   looseRecord,
//   mac,
//   maxLength,
//   minLength,
//   nanoid,
//   never,
//   null: _null,
//   nullable,
//   number,
//   object,
//   readonly,
//   record,
//   string,
//   tuple,
//   ulid,
//   union,
//   url,
//   uuid,
//   xid,
//   xor,
// };
// endregion

// #region for MCP (prune?)
export * from '../../node_modules/zod/v4/classic/checks.js';
export * as iso from '../../node_modules/zod/v4/classic/iso.js';
export * from '../../node_modules/zod/v4/classic/schemas.js';
export * as coerce from '../../node_modules/zod/v4/classic/coerce.js';
// #endregion
